name: AALTITOAD CMake Pipeline

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

env:
  BUILD_TYPE: Release
  GIT_SUBMODULE_STRATEGY: recursive

jobs:
  build-linux:
    if: ${{ github.event.pull_request.draft == false }}
    name: Build For Linux Systems
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Initialize Submodules
      uses: snickerbockers/submodules-init@v4
    - name: Install dependencies
      run: sudo apt-get install -y flex bison make
    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build
    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE
    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE -j$(nproc)
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: executable
        path: ${{ github.workspace }}/build/aaltitoad
  verification-tests:
    runs-on: ubuntu-latest
    needs: build-linux
    name: Verification Tests
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download executable
        uses: actions/download-artifact@v2
        with:
          name: executable
      - name: Make executable executable
        run: sudo chmod +x aaltitoad
      - name: fischer-2 
        working-directory: ${{ github.workspace }}/test/verification
        run: |
          ${{ github.workspace }}/aaltitoad -i ./fischer-2 -q ./fischer-2/Queries.json -o ./fischer-2/results.txt -v 6
          diff fischer-2/results.txt fischer-2/expected_results.ignore.txt
      - name: fischer-5
        working-directory: ${{ github.workspace }}/test/verification
        run: |
          ${{ github.workspace }}/aaltitoad -i ./fischer-5 -q ./fischer-5/Queries.json -o ./fischer-5/results.txt -v 6
          diff fischer-5/results.txt fischer-5/expected_results.ignore.txt
      - name: fischer-10
        working-directory: ${{ github.workspace }}/test/verification
        run: |
          ${{ github.workspace }}/aaltitoad -i ./fischer-10 -q ./fischer-10/Queries.json -o ./fischer-10/results.txt -v 6
          diff fischer-10/results.txt fischer-10/expected_results.ignore.txt
