name: AALTITOAD CMake Pipeline

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

env:
  BUILD_TYPE: Release
  GIT_SUBMODULE_STRATEGY: recursive
  CC: gcc-8
  CXX: g++-8

jobs:
  build-linux:
    name: Build For Linux Systems

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Initialize Submodules
      uses: snickerbockers/submodules-init@v4

    - name: Create Build Environment
      run: cmake -E make_directory ${{github.workspace}}/build

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

    - name: Build
      working-directory: ${{github.workspace}}/build
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: cmake --build . --config $BUILD_TYPE -j$(nproc)

  build-windows:
    name: Build For NT Systems
    runs-on: ubuntu-latest
    env:
      CC: "x86_64-w64-mingw32-gcc"
      CXX: "x86_64-w64-mingw32-g++"
      LD: "x86_64-w64-mingw32-ld"
      AR: "x86_64-w64-mingw32-ar"
      AS: "x86_64-w64-mingw32-as"
      NM: "x86_64-w64-mingw32-nm"
      STRIP: "x86_64-w64-mingw32-strip"
      RANLIB: "x86_64-w64-mingw32-ranlib"
      DLLTOOL: "x86_64-w64-mingw32-dlltool"
      OBJDUMP: "x86_64-w64-mingw32-objdump"
      RESCOMP: "x86_64-w64-mingw32-windres"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Initialize Submodules
        uses: snickerbockers/submodules-init@v4

      - name: Create Build Environment
        run: cmake -E make_directory ${{github.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{github.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{github.workspace}}/build
        shell: bash
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . --config $BUILD_TYPE -j$(nproc)
