name: aaltitoad build

on: 
  pull_request:
    branches: 
      - master
  push:
    branches: 
      - master

# TODO: matrix this
env:
  BUILD_TYPE: Release

jobs:
  build-linux:
    if: ${{ github.event.pull_request.draft == false }}
    name: build (ubuntu-latest)
    runs-on: ubuntu-latest
    steps:
    - name: checkout repository
      uses: actions/checkout@v4
    - name: install dependencies
      run: sudo apt-get install -y flex bison make m4 cmake libfl-dev libbison-dev libgrpc-dev
    - name: create build environment
      run: cmake -E make_directory ${{ github.workspace }}/build
    - name: configure
      shell: bash
      working-directory: ${{ github.workspace }}/build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install
    - name: build
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: cmake --build . --config $BUILD_TYPE --target all -j$(nproc)
    - name: install
      working-directory: ${{ github.workspace }}/build
      shell: bash
      run: cmake --install . --config $BUILD_TYPE --prefix ${{ github.workspace }}/install
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: aaltitoad
        path: ${{ github.workspace }}/install/

# TODO: Run catch2 unit tests with coverage and submit coverage reports
# - cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)/install
# - cmake --build . --config Release --target all -j 5
# - cmake --install . --prefix $(pwd)/install --config Release
# - cd install
# - cp lib/* bin
# - cd bin
# - ./verifier --help
